services:
  backend:
    build: .
    container_name: deno_backend
    ports:
      - "8000:8000"
    volumes:
      - ./public:/app/public
    env_file:
      - path: production.env
        required: true
    depends_on:
      - mongo
      - redis
    networks:
      - proxy-networks

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

networks:
  proxy-network:
    external: true