name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version
        uses: denolib/setup-deno@v2
        with:
          deno-version: '2.2.1'
      - name: Lint Deno Module
        run: deno fmt --check
      - name: Test Deno Module
        run: deno task dev
